// Generated by https://quicktype.io

export default class  DashboardDTo {
    ReportId:              number;
    ReportName:            string;
    DBQuery:               string;
   
    constructor(data:any)
    {
        this.ReportId=data.ReportId;
        this.ReportName=data.ReportName;
        this.DBQuery=data.DBQuery;

    }
}
